"use client";

import { useState, useRef, memo, useMemo, Suspense } from 'react';
import React from 'react';
import { ChevronUp, Eye, EyeOff } from 'lucide-react';

// Import custom hooks
import { useQuestionAnswer, useQuestionProgress, useQuestionBookmark, useQuestionView } from '@/hooks/questions';
import { useIsTabletOrSmaller } from '@/hooks/ui';
import { useAuth } from '@/hooks/auth';

// Import the new accordion components
import {
  AccordionItem,
  AccordionContent,
  AccordionTrigger,
} from "@/components/ui/accordion"; // Assuming this is the correct path

import { TabNav } from '@/components/ui/tab-nav';
import { AnswerDisplay } from './AnswerDisplay';
import { DifficultyTag } from './DifficultyTag';
import { BookmarkButton } from './BookmarkButton';

// Lazy load ResourceList component for better performance
const ResourceList = React.lazy(() => 
  import('./ResourceListRefactored').then(module => ({ default: module.ResourceList }))
);

// ResourceList loading fallback component
function ResourceListSkeleton() {
  return (
    <div className="mt-2 mb-4">
      <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-32 mb-3 animate-pulse"></div>
      <div className="grid gap-x-6 gap-y-4" style={{ gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }}>
        {[1, 2].map((i) => (
          <div key={i}>
            <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-16 mb-1.5 animate-pulse"></div>
            <div className="space-y-1">
              {[1, 2].map((j) => (
                <div key={j} className="flex items-center space-x-2">
                  <div className="w-4 h-4 bg-gray-200 dark:bg-gray-700 rounded animate-pulse flex-shrink-0"></div>
                  <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded flex-grow animate-pulse"></div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// Define QuestionType locally based on usage in topics/page.tsx
type QuestionType = {
  id: number;
  question_text: string;
  answer_text?: string | null;
  keywords?: string[] | string | null;
  difficulty?: string | null;
  category_id?: number | null;
  topic_id?: number | null;
  categories?: { 
    id: number;
    name: string;
    topic_id: number;
  };
};

interface QuestionWithAnswerProps {
  question: QuestionType;
  topicId?: number;
  domain?: string | undefined; // Add domain prop for optimization (can be undefined)
  onCompletionChange?: (questionId: number, isCompleted: boolean, topicId?: number, categoryId?: number) => void;
  isBookmarked: boolean;
  onBookmarkStatusChange?: (questionId: number, newStatus: boolean) => void;
  // This prop will be set by the parent Accordion based on its onValueChange
  // to let this component know if it's currently open, to trigger side effects.
  isOpen?: boolean; 
  onRequestClose?: () => void; // New prop to request closing the accordion item
}

function QuestionWithAnswerComponent({
  question,
  topicId,
  domain,
  onCompletionChange,
  isBookmarked: initialIsBookmarked,
  onBookmarkStatusChange,
  isOpen,
  onRequestClose,
}: QuestionWithAnswerProps) {
  const [isExpandedState, setIsExpandedState] = useState(isOpen || false);
  const [isResourcesVisible, setIsResourcesVisible] = useState(true);
  const [activeTab, setActiveTab] = useState('answer'); // 'answer' or 'resources'
  const answerRef = useRef<HTMLDivElement | null>(null);
  const isTabletOrSmaller = useIsTabletOrSmaller();

  // Computed values
  const hasPredefinedAnswer = useMemo(() => {
    return Boolean(question.answer_text &&
           !question.answer_text.toLowerCase().includes('generated by ai'));
  }, [question.answer_text]);

  const questionId = question.id;
  const actualCategoryId = useMemo(() => question.categories?.id ?? question.category_id ?? 0, [question.categories?.id, question.category_id]);
  const actualTopicId = useMemo(() => question.topic_id ?? topicId ?? 0, [question.topic_id, topicId]);

  // Custom hooks for state management
  const { isViewed } = useQuestionView({
    questionId,
    topicId: actualTopicId || undefined,
    categoryId: actualCategoryId || undefined,
    domain: domain || undefined,
    isOpen
  });

  const { isGenerating, generatedAnswer, error } = useQuestionAnswer({
    questionId,
    questionText: question.question_text,
    topicId: actualTopicId || undefined,
    categoryId: actualCategoryId || undefined,
    domain: domain || undefined,
    isOpen,
    isViewed,
    hasPredefinedAnswer,
    predefinedAnswer: question.answer_text || undefined
  });

  const { user } = useAuth();
  
  const { isCompleted: isCompletedState, scrollProgress, toggleCompletion } = useQuestionProgress({
    questionId,
    topicId: actualTopicId || undefined,
    categoryId: actualCategoryId || undefined,
    domain: domain || undefined,
    answerRef: answerRef as React.RefObject<HTMLDivElement | null>,
    isExpanded: isExpandedState,
    hasAnswer: Boolean(generatedAnswer || question.answer_text),
    onCompletionChange: onCompletionChange as (questionId: number, isCompleted: boolean, topicId?: number, categoryId?: number) => void,
    userId: user?.id || undefined
  });

  // Note: Completion status is now handled directly in useQuestionProgress hook

  const { isBookmarked: isBookmarkedState, handleBookmarkChange } = useQuestionBookmark({
    questionId,
    initialIsBookmarked,
    onBookmarkStatusChange,
    ...(actualTopicId && actualCategoryId && {
      topicId: actualTopicId,
      categoryId: actualCategoryId
    })
  });

  // Sync expansion state with isOpen prop
  React.useEffect(() => {
    setIsExpandedState(isOpen || false);
  }, [isOpen]);

  // Tab navigation items for mobile
  const tabItems = [
    {
      id: 'answer',
      label: 'Answer',
      onClick: () => setActiveTab('answer')
    },
    {
      id: 'resources',
      label: 'Resources',
      onClick: () => setActiveTab('resources')
    }
  ];

  // Handle tab change
  const handleTabChange = (tabId: string) => {
    setActiveTab(tabId);
  };

  return (
    <AccordionItem 
      value={questionId.toString()}
      className={`group border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden transition-all duration-300 shadow-sm hover:shadow-md ${
        isTabletOrSmaller ? 'mb-2' : 'mb-3'
      }`}
    >
      {/* Header with AccordionTrigger and Bookmark Button */}
      <div className="relative bg-white dark:bg-gray-800 group-data-[state=open]:bg-gray-50 dark:group-data-[state=open]:bg-gray-700/50 transition-colors">
        {/* Use AccordionTrigger with proper layout structure */}
        <AccordionTrigger 
          className={`text-left justify-start items-start ${
            isTabletOrSmaller ? 'px-3 py-2.5 pr-16' : 'px-4 py-3 pr-20'
          } [&>svg]:hidden hover:bg-gray-50 dark:hover:bg-gray-700/50 relative z-10 cursor-pointer w-full`}
          onClick={() => {
            console.log('🎯 Accordion trigger clicked for question:', questionId);
            // Don't preventDefault here - let the accordion handle the toggle
          }}
        >
          {/* Left side: Status icon and question content */}
          <div className="flex items-start flex-1 min-w-0">
            <div
              onClick={(e) => {
                e.stopPropagation();
                toggleCompletion();
              }}
              className="mr-2 w-5 h-5 flex-shrink-0 mt-1 hover:scale-110 transition-transform cursor-pointer"
              title={isCompletedState ? 'Mark as incomplete' : 'Mark as complete'}
              role="button"
              tabIndex={0}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault();
                  e.stopPropagation();
                  toggleCompletion();
                }
              }}
            >
              {isCompletedState ? (
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-500 dark:text-green-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                </svg>
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <circle cx="12" cy="12" r="10" />
                </svg>
              )}
            </div>
            <div className="flex-1 min-w-0 text-left">
              <div className={`font-medium text-gray-800 dark:text-gray-100 whitespace-normal break-words text-left ${
                isTabletOrSmaller ? 'text-sm leading-5' : 'text-base'
              }`}>
                {question.question_text || 'Question text not available'}
              </div>
              {question.difficulty && (
                <div className="mt-1 text-left">
                  <DifficultyTag difficulty={question.difficulty} />
                </div>
              )}
            </div>
          </div>
          
          {/* Custom chevron */}
          <svg 
            className="h-4 w-4 text-gray-500 dark:text-gray-400 transition-transform duration-200 group-data-[state=open]:rotate-180 flex-shrink-0" 
            fill="none" 
            stroke="currentColor" 
            viewBox="0 0 24 24"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </AccordionTrigger>
        
        {/* Bookmark button positioned absolutely outside the trigger */}
        {(actualCategoryId !== null && actualCategoryId !== undefined) && (
          <div className={`absolute top-1/2 -translate-y-1/2 z-20 ${
            isTabletOrSmaller ? 'right-8' : 'right-10'
          }`}>
            <BookmarkButton
              questionId={questionId}
              topicId={actualTopicId}
              categoryId={actualCategoryId}
              initialIsBookmarked={isBookmarkedState}
              onBookmarkChange={handleBookmarkChange}
            />
          </div>
        )}
      </div>

      <AccordionContent 
        className={`pt-0 text-sm text-gray-700 dark:text-gray-300 border-t border-gray-200 dark:border-gray-700/80 bg-white dark:bg-gray-800 relative ${
          isTabletOrSmaller ? 'px-3 pb-3' : 'px-4 pb-4'
        }`}
      >
        {/* Mobile Tab Navigation */}
        {isTabletOrSmaller && (
          <div className="pt-4 pb-4">
            <TabNav
              items={tabItems}
              activeTab={activeTab}
              onTabChange={handleTabChange}
              variant="button"
              className="justify-center"
            />
          </div>
        )}

        {/* Content Layout - Mobile: Single pane with tabs, Desktop: Two panes */}
        <div className={`w-full ${
          isTabletOrSmaller 
            ? 'space-y-3' 
            : 'pt-3 flex flex-col lg:flex-row gap-6 h-[calc(100vh-200px)] min-h-[700px]'
        }`}>
          
          {/* Mobile: Single pane based on active tab */}
          {isTabletOrSmaller ? (
            <div className="w-full">
              {activeTab === 'answer' ? (
                <div className="relative">
                  <div 
                    ref={answerRef}
                    className="max-h-[60vh] min-h-[300px] border border-gray-200 dark:border-gray-700 rounded-lg overflow-y-auto bg-white dark:bg-gray-800/50 shadow-sm"
                  >
                    <AnswerDisplay
                      answerText={(hasPredefinedAnswer ? question.answer_text : generatedAnswer) ?? null}
                      isLoading={isGenerating}
                      error={error}
                      isCompleted={isCompletedState}
                      scrollProgress={scrollProgress}
                    />
                  </div>
                  {/* Mobile progress bar */}
                  {!isCompletedState && scrollProgress >= 0 && scrollProgress < 90 && (
                    <div className="absolute bottom-0 left-0 right-0 z-40 bg-white dark:bg-gray-900 border-t border-gray-200 dark:border-gray-700 px-4 py-2 rounded-b-lg">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs text-gray-400 dark:text-gray-500">
                          Reading: {Math.round(scrollProgress)}%
                        </span>
                      </div>
                      <div className="bg-gray-100 dark:bg-gray-800 rounded-full h-1">
                        <div 
                          className="bg-blue-400 dark:bg-blue-500 h-1 rounded-full transition-all duration-300 ease-out"
                          style={{ width: `${Math.min(scrollProgress, 100)}%` }}
                        />
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="bg-white dark:bg-gray-800/50 py-4 rounded-lg shadow-sm">
                  <Suspense fallback={<ResourceListSkeleton />}>
                    <ResourceList 
                      questionId={questionId} 
                      isResourcesVisible={true}
                      onResourcesVisibilityChange={() => {}}
                    />
                  </Suspense>
                </div>
              )}
            </div>
          ) : (
            /* Desktop: Two-pane layout */
            <>
              {/* Left Pane - Generated Answer */}
              <div className={`flex-1 flex flex-col h-full ${isResourcesVisible ? 'lg:w-1/2' : 'lg:w-full'}`}>
                <div 
                  ref={answerRef}
                  className="flex-1 flex flex-col h-full border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden bg-white dark:bg-gray-800/50"
                >
                  <AnswerDisplay
                    answerText={(hasPredefinedAnswer ? question.answer_text : generatedAnswer) ?? null}
                    isLoading={isGenerating}
                    error={error}
                    isCompleted={isCompletedState}
                    scrollProgress={scrollProgress}
                  />
                </div>
              </div>
              
              {/* Right Pane - Resource Preview */}
              {isResourcesVisible && (
                <div className="flex-1 lg:w-1/2 flex flex-col h-full">
                  <div className="flex-1 flex flex-col h-full bg-white dark:bg-gray-800/50 rounded-lg overflow-hidden">
                    <div className="h-full">
                      <Suspense fallback={<ResourceListSkeleton />}>
                        <ResourceList 
                          questionId={questionId} 
                          isResourcesVisible={isResourcesVisible}
                          onResourcesVisibilityChange={setIsResourcesVisible}
                        />
                      </Suspense>
                    </div>
                  </div>
                </div>
              )}
            </>
          )}
        </div>

        {/* Desktop Controls - Only show on desktop when expanded */}
        {!isTabletOrSmaller && isExpandedState && onRequestClose && (
          <div className="mt-4 flex justify-between items-center">
            <button
              onClick={() => setIsResourcesVisible(!isResourcesVisible)}
              className="flex items-center text-xs text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 px-3 py-1.5 rounded-md transition-colors duration-150 h-8"
            >
              {isResourcesVisible ? (
                <>
                  <EyeOff className="mr-1 h-3.5 w-3.5" />
                  Hide Resources
                </>
              ) : (
                <>
                  <Eye className="mr-1 h-3.5 w-3.5" />
                  Show Resources
                </>
              )}
            </button>
            <button
              onClick={onRequestClose}
              className="flex items-center text-xs text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 px-3 py-1.5 rounded-md transition-colors duration-150 h-8"
            >
              <ChevronUp className="mr-1 h-3.5 w-3.5" />
              Collapse
            </button>
          </div>
        )}
      </AccordionContent>
    </AccordionItem>
  );
}

// Memoize the component for performance
export const QuestionWithAnswer = memo(QuestionWithAnswerComponent);