"use client";

import { useState, useEffect, useRef, memo, useMemo, useCallback, Suspense } from 'react';
import { isQuestionBookmarked, isQuestionCompleted, markQuestionAsCompleted, markQuestionAsViewed } from '@/app/utils/progress';
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';
import React from 'react';
import { toast } from '@/hooks/use-toast';

// Import the new components
import { QuestionHeader } from './QuestionHeader';
import { AnswerDisplay } from './AnswerDisplay';

// Lazy load ResourceList component for better performance
const ResourceList = React.lazy(() => 
  import('./ResourceList').then(module => ({ default: module.ResourceList }))
);

// ResourceList loading fallback component
function ResourceListSkeleton() {
  return (
    <div className="mt-2 mb-4">
      <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-32 mb-3 animate-pulse"></div>
      <div className="grid gap-x-6 gap-y-4" style={{ gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }}>
        {[1, 2].map((i) => (
          <div key={i}>
            <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-16 mb-1.5 animate-pulse"></div>
            <div className="space-y-1">
              {[1, 2].map((j) => (
                <div key={j} className="flex items-center space-x-2">
                  <div className="w-4 h-4 bg-gray-200 dark:bg-gray-700 rounded animate-pulse flex-shrink-0"></div>
                  <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded flex-grow animate-pulse"></div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// Define QuestionType locally based on usage in topics/page.tsx
type QuestionType = {
  id: number;
  question_text: string;
  answer_text?: string | null;
  keywords?: string[] | string | null;
  difficulty?: string | null;
  category_id?: number | null;
  topic_id?: number | null;
  categories?: { 
    id: number;
    name: string;
    topic_id: number;
  };
};

interface QuestionWithAnswerProps {
  question: QuestionType;
  questionIndex: number;
  isHighlighted?: boolean;
  topicId?: number;
  onCompletionChange?: (questionId: number, isCompleted: boolean) => void;
}

// Renaming original component and preparing for memoization
function QuestionWithAnswerComponent({ question, questionIndex, isHighlighted = false, topicId, onCompletionChange }: QuestionWithAnswerProps) {
  // Initialize Supabase client
  const supabase = createClientComponentClient();

  const [isExpanded, setIsExpanded] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedAnswer, setGeneratedAnswer] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isViewed, setIsViewed] = useState(false);
  const [isBookmarked, setIsBookmarked] = useState(false);
  const [isCompleted, setIsCompleted] = useState(false);
  const [scrollProgress, setScrollProgress] = useState(0);
  const answerRef = useRef<HTMLDivElement | null>(null);
  const scrollTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Memoize expensive calculations
  const hasPredefinedAnswer = useMemo(() => {
    return question.answer_text &&
           !question.answer_text.toLowerCase().includes('generated by ai');
  }, [question.answer_text]);

  const questionId = question.id;
  const categoryId = question.categories?.id ?? question.category_id;



  useEffect(() => {
    if (question.id) {
      console.log(`Checking status for question ${question.id}`);

      try {
        const localStorageCompletedQuestions = JSON.parse(localStorage.getItem('completedQuestions') || '[]');
        const sessionStorageCompletedQuestions = JSON.parse(sessionStorage.getItem('completedQuestions') || '[]');
        if (localStorageCompletedQuestions.includes(question.id) || 
            sessionStorageCompletedQuestions.includes(question.id)) {
          console.log(`Question ${question.id} found in client storage as completed`);
          setIsCompleted(true);
        }
      } catch (err) {
        console.error('Error checking client storage:', err);
      }

      isQuestionBookmarked(question.id)
        .then(bookmarked => {
          setIsBookmarked(bookmarked);
        })
        .catch(err => console.error('Failed to check bookmark status:', err));
      
      if (!isCompleted) {
        fetch(`/api/user/progress/status?questionId=${question.id}`, { headers: { 'Cache-Control': 'no-store' } })
        .then(response => response.json())
        .then(data => {
          if (data.status === 'completed') {
            setIsCompleted(true);
            try {
              const completedQuestions = JSON.parse(localStorage.getItem('completedQuestions') || '[]');
              if (!completedQuestions.includes(question.id)) {
                completedQuestions.push(question.id);
                localStorage.setItem('completedQuestions', JSON.stringify(completedQuestions));
              }
            } catch (err) {
              console.error('Error updating localStorage after API check:', err);
            }
          }
        })
        .catch(err => {
          console.error(`Error checking status for question ${question.id}:`, err);
        });
      }
    }
  }, [question.id, isCompleted]);

  useEffect(() => {
    if (isExpanded && !isViewed && question.id) {
      markQuestionAsViewed(question.id, question.topic_id, question.category_id)
        .then((success) => {
          if (success) {
            setIsViewed(true);
            console.log(`Question ${question.id} marked as viewed successfully`);
          } else {
            console.error(`Failed to mark question ${question.id} as viewed`);
          }
        })
        .catch(err => console.error('Failed to mark question as viewed:', err));
    }
  }, [isExpanded, isViewed, question.id, question.topic_id, question.category_id]);

  useEffect(() => {
    const answerIsReady = isExpanded && 
                         ((hasPredefinedAnswer && question.answer_text) || 
                          (!hasPredefinedAnswer && generatedAnswer && !isGenerating));

    if (!answerIsReady || !answerRef.current || !question.id) return;

    const answerElement = answerRef.current;
    setScrollProgress(0);

    const calculateScrollProgress = () => {
      if (!answerElement) return;
      const totalHeight = answerElement.scrollHeight - answerElement.clientHeight;
      let percentage: number;
      if (totalHeight <= 0) {
        percentage = 100;
      } else {
        const scrollPosition = answerElement.scrollTop;
        percentage = Math.min(Math.round((scrollPosition / totalHeight) * 100), 100);
      }
      setScrollProgress(percentage);

      console.log(`Question ${question.id} scroll progress: ${percentage}%, isCompleted: ${isCompleted}`);

      if (percentage >= 90 && !isCompleted && question.id) {
        console.log(`Scroll progress reached ${percentage}%, optimistically marking question ${question.id} as completed`);
        
        // Optimistic UI update
        setIsCompleted(true);
        onCompletionChange?.(question.id, true);
        toast.success("Question marked as completed!");

        markQuestionAsCompleted(question.id, topicId || 0, categoryId || 0)
          .then((success) => {
            if (success) {
              console.log(`Question ${question.id} marked as completed in database`);
              try {
                const completedQuestions = JSON.parse(localStorage.getItem('completedQuestions') || '[]');
                if (!completedQuestions.includes(question.id)) {
                  completedQuestions.push(question.id);
                  localStorage.setItem('completedQuestions', JSON.stringify(completedQuestions));
                  console.log(`Question ${question.id} added to localStorage completed list`);
                }
              } catch (storageError) { console.error('Error updating localStorage:', storageError); }
              try {
                const completedSessionQuestions = JSON.parse(sessionStorage.getItem('completedQuestions') || '[]');
                 if (!completedSessionQuestions.some((q: any) => q.questionId === question.id)) {
                    completedSessionQuestions.push({
                      questionId: question.id,
                      topicId: topicId,
                      categoryId: categoryId,
                    });
                    sessionStorage.setItem('completedQuestions', JSON.stringify(completedSessionQuestions));
                    console.log(`Added question ${question.id} to completedQuestions in sessionStorage`);
                 }
              } catch (storageError) { console.error('Error storing completed question in session storage:', storageError); }
            } else {
              console.error(`Failed to mark question ${question.id} as completed`);
              // Revert optimistic update on failure
              setIsCompleted(false);
              onCompletionChange?.(question.id, false);
              toast.error("Failed to mark question as completed. Please try again.");
            }
          })
          .catch(err => {
            console.error('Failed to mark question as completed:', err);
            // Revert optimistic update on error
            setIsCompleted(false);
            onCompletionChange?.(question.id, false);
            toast.error("An error occurred. Please try again.");
          });
      }
    };

    const handleScroll = () => {
      if (scrollTimeoutRef.current) clearTimeout(scrollTimeoutRef.current);
      scrollTimeoutRef.current = setTimeout(calculateScrollProgress, 100);
    };

    const initialTimer = setTimeout(calculateScrollProgress, 500);
    answerElement.addEventListener('scroll', handleScroll);

    return () => {
      if (scrollTimeoutRef.current) clearTimeout(scrollTimeoutRef.current);
      clearTimeout(initialTimer);
      if (answerElement) answerElement.removeEventListener('scroll', handleScroll);
    };
  }, [isExpanded, question.id, topicId, categoryId, generatedAnswer, hasPredefinedAnswer, isGenerating, question.answer_text, isCompleted, onCompletionChange]);

  useEffect(() => {
    if (isExpanded && !hasPredefinedAnswer && !generatedAnswer && !isGenerating && !error) {
      const generateAnswer = async () => {
        setIsGenerating(true);
        setError(null);
        try {
          console.log(`Generating answer for question: ${question.id} - ${question.question_text}`);
          const response = await fetch('/api/generate-answer', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ questionText: question.question_text, questionId: question.id }),
          });
          const data = await response.json();
          console.log("API Response:", data);
          if (!response.ok) {
            setError(data.message || data.error || 'Failed to generate answer');
            setGeneratedAnswer(null);
          } else if (data.answer === null && data.message) {
            setError(data.message);
            setGeneratedAnswer(null);
          } else {
            setGeneratedAnswer(data.answer || 'No answer content received.');
          }
        } catch (err: unknown) { 
          console.error("Generation fetch error:", err);
          setError(err instanceof Error ? err.message : 'An unexpected error occurred.');
          setGeneratedAnswer(null);
        } finally { setIsGenerating(false); }
      };
      generateAnswer();
    }
  }, [isExpanded, hasPredefinedAnswer, generatedAnswer, isGenerating, error, question.id, question.question_text]);

  const toggleExpansion = () => {
    setIsExpanded(!isExpanded);
    if (isExpanded) {
      setError(null);
    }
  };

  const handleBookmarkChange = useCallback((newBookmarkStatus: boolean) => {
    setIsBookmarked(newBookmarkStatus);
  }, []);



  const handleSetAnswerRef = useCallback((el: HTMLDivElement | null) => {
    answerRef.current = el;
  }, []);

  console.log(`Rendering QuestionWithAnswer for question ${question.id}, isCompleted=${isCompleted}`);

  return (
    <div 
      id={`question-${question.id}`}
      className={`border-t border-b border-gray-200 dark:border-gray-700 transition-all duration-200 ${
        isHighlighted 
          ? 'bg-yellow-50 dark:bg-yellow-900/20 border-yellow-400 dark:border-yellow-600' 
          : 'bg-white dark:bg-gray-900'
      }`}
    >
      <div className="py-6 px-0">
        <div className="flex items-center justify-between cursor-pointer" onClick={toggleExpansion}>
          <h3 className="text-lg font-normal text-gray-900 dark:text-gray-100 pr-8 leading-relaxed">
            {question.question_text}
          </h3>
          <div className="flex items-center space-x-3">
            {/* Completion and bookmark indicators */}
            <div className="flex items-center space-x-2">
              {isCompleted && (
                <div title="Completed">
                  <svg 
                    className="w-5 h-5 text-green-500" 
                    fill="none" 
                    stroke="currentColor" 
                    viewBox="0 0 24 24"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                </div>
              )}
              {isBookmarked && (
                <div className="w-2 h-2 bg-blue-500 rounded-full" title="Bookmarked"></div>
              )}
            </div>
            
            {/* Expand/collapse arrow */}
            <svg 
              className={`w-5 h-5 text-gray-400 transition-transform duration-200 ${isExpanded ? 'rotate-180' : ''}`}
              fill="none" 
              stroke="currentColor" 
              viewBox="0 0 24 24"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </div>
        </div>

        {isExpanded && (
          <div className="mt-6 pt-6 border-t border-gray-100 dark:border-gray-800">
            {/* Display additional resources first */}
            <React.Suspense fallback={<ResourceListSkeleton />}>
              <ResourceList questionId={questionId} />
            </React.Suspense>
            
            <AnswerDisplay
              answerText={(hasPredefinedAnswer ? question.answer_text : generatedAnswer) ?? null}
              isLoading={isGenerating}
              error={error}
              scrollProgress={scrollProgress}
              isCompleted={isCompleted}
              setAnswerRef={handleSetAnswerRef}
            />
          </div>
        )}
      </div>
    </div>
  );
}

// Exporting the memoized component
export const QuestionWithAnswer = memo(QuestionWithAnswerComponent);