"use client";

import { useState, useRef, memo, useMemo, Suspense } from 'react';
import React from 'react';
import { ChevronUp } from 'lucide-react';


// Import custom hooks
import { useQuestionAnswer, useQuestionProgress, useQuestionBookmark, useQuestionView } from '@/hooks/questions';

// Import the new accordion components
import {
  AccordionItem,
  AccordionContent,
  AccordionTrigger,
} from "@/components/ui/accordion"; // Assuming this is the correct path

import { BookmarkButton } from './BookmarkButton'; // Keep BookmarkButton
import { AnswerDisplay } from './AnswerDisplay';
import { DifficultyTag } from './DifficultyTag';

// Lazy load ResourceList component for better performance
const ResourceList = React.lazy(() => 
  import('./ResourceListRefactored').then(module => ({ default: module.ResourceList }))
);

// ResourceList loading fallback component
function ResourceListSkeleton() {
  return (
    <div className="mt-2 mb-4">
      <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-32 mb-3 animate-pulse"></div>
      <div className="grid gap-x-6 gap-y-4" style={{ gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }}>
        {[1, 2].map((i) => (
          <div key={i}>
            <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-16 mb-1.5 animate-pulse"></div>
            <div className="space-y-1">
              {[1, 2].map((j) => (
                <div key={j} className="flex items-center space-x-2">
                  <div className="w-4 h-4 bg-gray-200 dark:bg-gray-700 rounded animate-pulse flex-shrink-0"></div>
                  <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded flex-grow animate-pulse"></div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// Define QuestionType locally based on usage in topics/page.tsx
type QuestionType = {
  id: number;
  question_text: string;
  answer_text?: string | null;
  keywords?: string[] | string | null;
  difficulty?: string | null;
  category_id?: number | null;
  topic_id?: number | null;
  categories?: { 
    id: number;
    name: string;
    topic_id: number;
  };
};

interface QuestionWithAnswerProps {
  question: QuestionType;
  questionIndex: number;
  topicId?: number;
  domain?: string | undefined; // Add domain prop for optimization (can be undefined)
  onCompletionChange?: (questionId: number, isCompleted: boolean, topicId?: number, categoryId?: number) => void;
  isBookmarked: boolean;
  onBookmarkStatusChange?: (questionId: number, newStatus: boolean) => void;
  // This prop will be set by the parent Accordion based on its onValueChange
  // to let this component know if it's currently open, to trigger side effects.
  isOpen?: boolean; 
  onRequestClose?: () => void; // New prop to request closing the accordion item
}

function QuestionWithAnswerComponent({
  question,
  questionIndex,
  topicId,
  domain,
  onCompletionChange,
  isBookmarked: initialIsBookmarked,
  onBookmarkStatusChange,
  isOpen,
  onRequestClose
}: QuestionWithAnswerProps) {
  const [isExpandedState, setIsExpandedState] = useState(isOpen || false);
  const [isResourcesVisible, setIsResourcesVisible] = useState(true);
  const answerRef = useRef<HTMLDivElement | null>(null);

  // Computed values
  const hasPredefinedAnswer = useMemo(() => {
    return Boolean(question.answer_text &&
           !question.answer_text.toLowerCase().includes('generated by ai'));
  }, [question.answer_text]);

  const questionId = question.id;
  const actualCategoryId = useMemo(() => question.categories?.id ?? question.category_id ?? 0, [question.categories?.id, question.category_id]);
  const actualTopicId = useMemo(() => question.topic_id ?? topicId ?? 0, [question.topic_id, topicId]);

  // Custom hooks for state management
  const { isViewed } = useQuestionView({
    questionId,
    topicId: actualTopicId || undefined,
    categoryId: actualCategoryId || undefined,
    domain: domain || undefined,
    isOpen
  });

  const { isGenerating, generatedAnswer, error } = useQuestionAnswer({
    questionId,
    questionText: question.question_text,
    topicId: actualTopicId || undefined,
    categoryId: actualCategoryId || undefined,
    domain: domain || undefined,
    isOpen,
    isViewed,
    hasPredefinedAnswer,
    predefinedAnswer: question.answer_text || undefined
  });

  const { isCompleted: isCompletedState, scrollProgress } = useQuestionProgress({
    questionId,
    topicId: actualTopicId || undefined,
    categoryId: actualCategoryId || undefined,
    domain: domain || undefined,
    answerRef: answerRef as React.RefObject<HTMLDivElement | null>,
    isExpanded: isExpandedState,
    hasAnswer: Boolean(generatedAnswer || question.answer_text),
    onCompletionChange: onCompletionChange as (questionId: number, isCompleted: boolean, topicId?: number, categoryId?: number) => void
  });

  // Note: Completion status is now handled directly in useQuestionProgress hook

  const { isBookmarked: isBookmarkedState, handleBookmarkChange } = useQuestionBookmark({
    questionId,
    initialIsBookmarked,
    onBookmarkStatusChange
  });

  // Sync expansion state with isOpen prop
  React.useEffect(() => {
    setIsExpandedState(isOpen || false);
  }, [isOpen]);

  // No need for separate bookmark handler - using custom hook


  return (
    <AccordionItem 
      value={questionId.toString()}
      className="group border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden transition-all duration-300 shadow-sm hover:shadow-md mb-3"
    >
      <div className="flex items-start justify-between w-full bg-white dark:bg-gray-800 group-data-[state=open]:bg-gray-50 dark:group-data-[state=open]:bg-gray-700/50 transition-colors">
        <AccordionTrigger className="flex items-start justify-between flex-1 px-4 py-3 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2">
          <div className="flex items-start flex-1 pr-3 min-w-0"> {/* Ensure text wraps */}
            {isCompletedState ? (
              <div className="mr-2 text-green-500 dark:text-green-400 flex-shrink-0 mt-1">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                </svg>
              </div>
            ) : (
              <div className="mr-2 w-5 h-5 flex-shrink-0 mt-1"> {/* Placeholder for alignment */}
                 <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400 dark:text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <circle cx="12" cy="12" r="10" />
                </svg>
              </div>
            )}
            <div className="flex-1 min-w-0">
              <div className="text-base font-medium text-gray-800 dark:text-gray-100 whitespace-normal break-words">
                {question.question_text || 'Question text not available'}
              </div>
              {question.difficulty && (
                <div className="mt-1">
                  <DifficultyTag difficulty={question.difficulty} />
                </div>
              )}
            </div>
          </div>
          
          <div className="flex items-center flex-shrink-0 space-x-2 pl-2">
            <span className="text-xs text-gray-500 dark:text-gray-400 group-data-[state=open]:text-gray-700 dark:group-data-[state=open]:text-gray-200">
              Q{questionIndex + 1}
            </span>
            {/* Default Radix ChevronDownIcon will be rendered by AccordionTrigger from ui/accordion.tsx */}
          </div>
        </AccordionTrigger>
        
        {/* Bookmark button outside the trigger to avoid nested buttons */}
        {(actualCategoryId !== null && actualCategoryId !== undefined) && (
          <div className="flex items-center px-2 py-3">
            <BookmarkButton
              questionId={questionId}
              topicId={actualTopicId ?? null} 
              categoryId={actualCategoryId}
              initialIsBookmarked={isBookmarkedState}
              onBookmarkChange={handleBookmarkChange} 
            />
          </div>
        )}
      </div>

      <AccordionContent 
        className="px-4 pt-0 pb-4 text-sm text-gray-700 dark:text-gray-300 border-t border-gray-200 dark:border-gray-700/80 bg-white dark:bg-gray-800 relative"
      >
        {/* Two-pane layout */}
        <div className="flex flex-col lg:flex-row gap-6 pt-3 h-[calc(100vh-200px)] min-h-[700px] w-full">
          {/* Left Pane - Generated Answer */}
          <div className={`flex-1 flex flex-col h-full ${isResourcesVisible ? 'lg:w-1/2' : 'lg:w-full'}`}>

            <div 
              ref={answerRef}
              className="flex-1 flex flex-col h-full border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden bg-white dark:bg-gray-800/50"
            >
              <AnswerDisplay
                answerText={(hasPredefinedAnswer ? question.answer_text : generatedAnswer) ?? null}
                isLoading={isGenerating}
                error={error}
                isCompleted={isCompletedState}
                scrollProgress={scrollProgress}
              />
            </div>
          </div>
          
          {/* Right Pane - Resource Preview */}
          {isResourcesVisible && (
            <div className="flex-1 lg:w-1/2 flex flex-col h-full">

              <div className="flex-1 flex flex-col h-full border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden bg-white dark:bg-gray-800/50">
                <div className="h-full overflow-y-auto">
                  <Suspense fallback={<ResourceListSkeleton />}>
                    <ResourceList 
                      questionId={questionId} 
                      isResourcesVisible={isResourcesVisible}
                      onResourcesVisibilityChange={setIsResourcesVisible}
                    />
                  </Suspense>
                </div>
              </div>
            </div>
          )}
        </div>

        {isExpandedState && onRequestClose && (
          <div className="mt-4 flex justify-between items-center">
            <button
              onClick={() => setIsResourcesVisible(!isResourcesVisible)}
              className="flex items-center text-xs text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 px-3 py-1.5 rounded-md transition-colors duration-150 h-8"
            >
              {isResourcesVisible ? (
                <>
                  <svg className="mr-1 h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.878 9.878L8.464 8.464M9.878 9.878a3 3 0 00-4.243 4.243m7.071 0l2.121-2.121M14.121 14.121L16.243 16.243M14.121 14.121a3 3 0 01-4.243-4.243m7.071 0a3 3 0 00-4.243-4.243" />
                  </svg>
                  Hide Resources
                </>
              ) : (
                <>
                  <svg className="mr-1 h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                  </svg>
                  Show Resources
                </>
              )}
            </button>
            <button
              onClick={onRequestClose}
              className="flex items-center text-xs text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 px-3 py-1.5 rounded-md transition-colors duration-150 h-8"
            >
              <ChevronUp className="mr-1 h-3.5 w-3.5" />
              Collapse
            </button>
          </div>
        )}
      </AccordionContent>
    </AccordionItem>
  );
}

// Memoize the component for performance
export const QuestionWithAnswer = memo(QuestionWithAnswerComponent);